name: Packaging
on:
  push:
   branches: 
    - 5.39.1-patches

env:
  base_version: 5.39.1

jobs:
  build:
    name: Packaging
    runs-on: ubuntu-latest

    steps:
      - name: Download Civi
        env:
          civi_package: civicrm-${{ env.base_version }}-drupal.tar.gz
        run: |
          cd ..
          pwd
          mkdir to-be-patched
          wget https://storage.googleapis.com/civicrm/civicrm-stable/${base_version}/${civi_package}
          tar xzf ./${civi_package} -C to-be-patched

      - name: Ckeditor security upgrade
        run: |
          cd ..
          rm -rf to-be-patched/civicrm/bower_components/ckeditor/
          wget https://github.com/ckeditor/ckeditor-releases/archive/4.18.0.tar.gz
          tar xzf 4.18.0.tar.gz
          mv ckeditor4-releases-4.18.0 to-be-patched/civicrm/bower_components/ckeditor/

      - name: jqueryUI security upgrade
        run: |
          cd ..
          rm -rf to-be-patched/civicrm/bower_components/jquery-ui/
          wget https://github.com/civicrm/jqueryui/archive/1.13.1-civicrm.tar.gz
          tar xzf 1.13.1-civicrm.tar.gz
          mv jqueryui-1.13.1-civicrm to-be-patched/civicrm/bower_components/jquery-ui/

      - name: Apply Dompdf patch "civi-sa-2022-06-dompdf-121"
        run: |
          cd ..
          rm -rf to-be-patched/civicrm/vendor/dompdf/
          wget https://github.com/dompdf/dompdf/archive/refs/tags/v2.0.3.tar.gz
          tar xzf v2.0.3.tar.gz
          mv dompdf-2.0.3 to-be-patched/civicrm/vendor/dompdf/

      - name: Checkout the fork
        uses: actions/checkout@v2
        with:
          ref: ${{ env.base_version }}

      - name: Create patched package
        uses: 'compucorp/create-patch-from-fork@1.0.0'
        id: "patch"
        with:
          base_version: ${{ env.base_version }}
          project_dir: '../to-be-patched/civicrm'
          project_name: 'civicrm'
          project_type: 'civicrm-core'

      - name: Create a new release
        id: create_release
        uses: compucorp/create-release@target_commitish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ steps.patch.outputs.version }}"
          target_commitish: "${{ github.sha }}"
          release_name: "${{ steps.patch.outputs.version }}"
          body: "${{ steps.patch.outputs.version }}"

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "${{ steps.patch.outputs.package_path }}"
          asset_name: "${{ steps.patch.outputs.package }}"
          asset_content_type: application/gzip
